### ISSUE TITLE
[suggestion]Add exclude band support?

### ISSUE THREAD

**Issue by Chengcheng-Xiao** [mturiansky/wavecar2unk#1]
Hi there Mark,

First of all, great job implementing this in `pymatgen`!

I've tried your code and found some stuff that I'd like to share:

1. The number of grid points on each axis is different than `NGX`, `NGY` and `NGZ`.
2. One can not specify which band they want to include.

Well, for the first one, I'm not sure if it's the default behavior of VASP. If it is, then never mind...

And for the other one, I think most users use `exclude_bands` do exclude those dispersion less semi-core states and implementing this function would be awesome!

P.S. I've Included this function to my [`fix`](https://github.com/Chengcheng-Xiao/VASP2WAN90_v2_fix) so one can calculate these stuff directly from VASP without the hassle of rerun a NSCF calculation! Cheers!

**Comment by mturiansky** [comment]
Thanks for the suggestion, and thanks for providing the patch, it's been quite useful.

I should have mentioned somewhere that the mesh can be chosen quite easily here. I also will add a command line option to the interface for this. Essentially, you can do the following:
```python
import numpy as np
from pymatgen.io.vasp.outputs import Wavecar

w = Wavecar('WAVECAR')
w.ng = np.array([ngx, ngy, ngz])
w.write_unks('unks/')
```
I'll definitely add the exclude band support. For the specific project that I'm working on, I want all the bands, so the thought hadn't crossed my mind.

**Comment by Chengcheng-Xiao** [comment]
Ah, I see! 
Since you are doing inverse Fourier transformation you can easily choose the grid size! 
Hum🧐, this can be quite useful for stuff like real-space integrations (less aliasing error I guess). 

Anyhow, good luck with your project! Issue closed for now🤗
